Repository OCA/website, pull requests merged in 2018-04, with the labels that each got.

#441 [10.0] website_multi_theme: Backport for theme_customize_get fix
  website_multi_theme/__init__.py
  website_multi_theme/__manifest__.py
  website_multi_theme/controllers/__init__.py
  website_multi_theme/controllers/main.py
Labels: bug, needs review

#442 10.0 website multi theme fix data is not defined
  website_multi_theme/__manifest__.py
  website_multi_theme/models/website.py
  website_multi_theme/tests/__init__.py
  website_multi_theme/tests/test_themes.py
Labels: bug, needs review

#444 [FIX] website_multi_theme: Manage only Qweb views
  website_multi_theme/__manifest__.py
  website_multi_theme/migrations/10.0.1.1.0/pre-migrate.py
  website_multi_theme/models/website_theme.py
Labels: needs review

#447 [FIX] website_multi_theme: Take into account disabled views
  website_multi_theme/__manifest__.py
  website_multi_theme/models/website_theme.py
Labels: bug, needs review

#440 [FIX] website_form_builder: Usability fixes
  website_form_builder/__manifest__.py
  website_form_builder/static/src/js/snippets.js
  website_form_builder/static/src/xml/snippets.xml
  website_form_builder/templates/snippets.xml
Labels: bug, enhancement, needs review

#446 [MIG] website_crm_privacy_policy: Migration to 11.0
  website_crm_privacy_policy/README.rst
  website_crm_privacy_policy/__init__.py
  website_crm_privacy_policy/__manifest__.py
  website_crm_privacy_policy/i18n/ca.po
  website_crm_privacy_policy/i18n/de.po
  website_crm_privacy_policy/i18n/el_GR.po
  website_crm_privacy_policy/i18n/es.po
  website_crm_privacy_policy/i18n/fr.po
  website_crm_privacy_policy/i18n/it.po
  website_crm_privacy_policy/i18n/pt_BR.po
  website_crm_privacy_policy/i18n/ru.po
  website_crm_privacy_policy/i18n/sl.po
  website_crm_privacy_policy/static/description/icon.png
  website_crm_privacy_policy/templates/contactus.xml
Labels: needs review
