Repository OCA/website, pull requests merged in 2019-06, with the labels that each got.

#642 [ADD] website_hr_recruitment_legal: Legal stuff for job recruitment
  website_hr_recruitment_legal/README.rst
  website_hr_recruitment_legal/__init__.py
  website_hr_recruitment_legal/__manifest__.py
  website_hr_recruitment_legal/readme/CONTRIBUTORS.rst
  website_hr_recruitment_legal/readme/DESCRIPTION.rst
  website_hr_recruitment_legal/readme/USAGE.rst
  website_hr_recruitment_legal/static/description/icon.png
  website_hr_recruitment_legal/static/description/index.html
  website_hr_recruitment_legal/templates/apply.xml
Labels: approved, needs review, ready to merge

#646 [11.0][FIX] website_form_builder: Fix modal select view
  website_form_builder/static/src/css/website_form_builder.less
  website_form_builder/static/src/xml/widgets.xml
Labels: approved

#595 [12.0][MIG] website_media_size: Migration to v12
  website_media_size/README.rst
  website_media_size/__init__.py
  website_media_size/__manifest__.py
  website_media_size/i18n/website_media_size.pot
  website_media_size/readme/CONTRIBUTORS.rst
  website_media_size/readme/DESCRIPTION.rst
  website_media_size/readme/USAGE.rst
  website_media_size/static/description/icon.png
  website_media_size/static/description/screenshot.png
  website_media_size/static/src/js/website_media_size.js
  website_media_size/static/src/scss/website_media_size.scss
  website_media_size/static/src/xml/website_media_size.xml
  website_media_size/templates/assets.xml
Labels: approved, needs fixing, ready to merge

#581 [12.0] [MIG] website_blog_excerpt_image: Migration to v12
  oca_dependencies.txt
  website_blog_excerpt_img/README.rst
  website_blog_excerpt_img/__init__.py
  website_blog_excerpt_img/__manifest__.py
  website_blog_excerpt_img/i18n/bg.po
  website_blog_excerpt_img/i18n/de.po
  website_blog_excerpt_img/i18n/el_GR.po
  website_blog_excerpt_img/i18n/es.po
  website_blog_excerpt_img/i18n/eu.po
  website_blog_excerpt_img/i18n/fr.po
  website_blog_excerpt_img/i18n/hr.po
  website_blog_excerpt_img/i18n/hr_HR.po
  website_blog_excerpt_img/i18n/it.po
  website_blog_excerpt_img/i18n/nb_NO.po
  website_blog_excerpt_img/i18n/pt_BR.po
  website_blog_excerpt_img/i18n/sl.po
  website_blog_excerpt_img/i18n/website_blog_excerpt_img.pot
  website_blog_excerpt_img/i18n/zh_CN.po
  website_blog_excerpt_img/models/__init__.py
  website_blog_excerpt_img/models/blog_post.py
  website_blog_excerpt_img/readme/CONTRIBUTORS.rst
  website_blog_excerpt_img/readme/DESCRIPTION.rst
  website_blog_excerpt_img/readme/INSTALL.rst
  website_blog_excerpt_img/readme/USAGE.rst
  website_blog_excerpt_img/static/description/icon.png
  website_blog_excerpt_img/static/description/index.html
  website_blog_excerpt_img/static/description/post-list.png
  website_blog_excerpt_img/templates/blog.xml
Labels: needs review
