Repository OCA/website, pull requests merged in 2019-10, with the labels that each got.

#665 [FIX] website_no_crawler: Revert on uninstall
  website_no_crawler/views/disable_robots.xml
Labels: approved, bug, needs review, ready to merge

#668 [FIX] website_no_crawler: Revert on uninstall
  website_no_crawler/views/disable_robots.xml
Labels: bug

#669 [12.0][IMP] website_snippet_country_dropdown: custom input field classes
  website_snippet_country_dropdown/views/snippets.xml
Labels: approved
