Repository OCA/website, pull requests merged in 2019-05, with the labels that each got.

#573 [12.0][MIG] website_crm_recaptcha: Migration to v12
  website_crm_recaptcha/README.rst
  website_crm_recaptcha/__init__.py
  website_crm_recaptcha/__manifest__.py
  website_crm_recaptcha/data/ir_model_data.xml
  website_crm_recaptcha/i18n/hr.po
  website_crm_recaptcha/i18n/website_crm_recaptcha.pot
  website_crm_recaptcha/i18n/zh_CN.po
  website_crm_recaptcha/readme/CONFIGURATION.rst
  website_crm_recaptcha/readme/CONTRIBUTORS.rst
  website_crm_recaptcha/readme/DESCRIPTION.rst
  website_crm_recaptcha/readme/USAGE.rst
  website_crm_recaptcha/static/description/icon.png
  website_crm_recaptcha/static/description/index.html
  website_crm_recaptcha/static/description/website_crm_recaptcha.jpg
  website_crm_recaptcha/views/website_crm_template.xml
Labels: approved, migration, ready to merge

#582 [FIX] website_cookie_notice: max-age for cookie
  website_cookie_notice/README.rst
  website_cookie_notice/__manifest__.py
  website_cookie_notice/static/src/js/accept_cookies.js
Labels: approved, enhancement

#630 [12.0][MIG] website_snippet_country_dropdown
  website_snippet_country_dropdown/README.rst
  website_snippet_country_dropdown/__init__.py
  website_snippet_country_dropdown/__manifest__.py
  website_snippet_country_dropdown/demo/assets.xml
  website_snippet_country_dropdown/demo/pages.xml
  website_snippet_country_dropdown/i18n/en.po
  website_snippet_country_dropdown/i18n/es.po
  website_snippet_country_dropdown/i18n/fr.po
  website_snippet_country_dropdown/i18n/sl.po
  website_snippet_country_dropdown/i18n/website_snippet_country_dropdown.pot
  website_snippet_country_dropdown/readme/CONTRIBUTORS.rst
  website_snippet_country_dropdown/readme/DESCRIPTION.rst
  website_snippet_country_dropdown/readme/ROADMAP.rst
  website_snippet_country_dropdown/readme/USAGE.rst
  website_snippet_country_dropdown/static/description/icon.png
  website_snippet_country_dropdown/static/description/index.html
  website_snippet_country_dropdown/static/src/css/style.scss
  website_snippet_country_dropdown/static/src/js/web_tour_country_dropdown.js
  website_snippet_country_dropdown/static/src/js/website_snippet_country_dropdown.js
  website_snippet_country_dropdown/static/src/xml/country_dropdown.xml
  website_snippet_country_dropdown/tests/__init__.py
  website_snippet_country_dropdown/tests/test_snippet_country_dropdown.py
  website_snippet_country_dropdown/views/assets.xml
  website_snippet_country_dropdown/views/snippets.xml
Labels: approved

#631 [MIG] website_form_builder: Migration to 12.0
  website_form_builder/README.rst
  website_form_builder/__init__.py
  website_form_builder/__manifest__.py
  website_form_builder/demo/assets.xml
  website_form_builder/demo/ir_model.xml
  website_form_builder/i18n/es.po
  website_form_builder/i18n/website_form_builder.pot
  website_form_builder/readme/CONFIGURE.rst
  website_form_builder/readme/CONTRIBUTORS.rst
  website_form_builder/readme/CREDITS.rst
  website_form_builder/readme/DESCRIPTION.rst
  website_form_builder/readme/INSTALL.rst
  website_form_builder/readme/ROADMAP.rst
  website_form_builder/readme/USAGE.rst
  website_form_builder/static/description/icon.png
  website_form_builder/static/description/icon.svg
  website_form_builder/static/description/index.html
  website_form_builder/static/src/css/website_form_builder.scss
  website_form_builder/static/src/js/snippets.js
  website_form_builder/static/src/js/tour.js
  website_form_builder/static/src/js/widgets.js
  website_form_builder/static/src/xml/snippets.xml
  website_form_builder/static/src/xml/widgets.xml
  website_form_builder/templates/assets.xml
  website_form_builder/templates/snippets.xml
  website_form_builder/tests/__init__.py
  website_form_builder/tests/test_ui.py
  website_form_builder/views/ir_model.xml
Labels: approved
