Repository OCA/website, pull requests merged in 2019-03, with the labels that each got.

#576 [12.0][FIX] website_google_tag_manager: Fix travis error
  website_google_tag_manager/README.rst
  website_google_tag_manager/readme/DESCRIPTION.rst
Labels: approved

#558 12.0 website js below the fold
  website_google_tag_manager/README.rst
  website_js_below_the_fold/README.rst
  website_js_below_the_fold/__init__.py
  website_js_below_the_fold/__manifest__.py
  website_js_below_the_fold/i18n/website_js_below_the_fold.pot
  website_js_below_the_fold/readme/CONTRIBUTORS.rst
  website_js_below_the_fold/readme/DESCRIPTION.rst
  website_js_below_the_fold/readme/USAGE.rst
  website_js_below_the_fold/templates/website_js_below_the_fold.xml
Labels: approved, ready to merge

#583 [12.0][MIG] website_anchor_smooth_scroll
  website_anchor_smooth_scroll/README.rst
  website_anchor_smooth_scroll/__init__.py
  website_anchor_smooth_scroll/__manifest__.py
  website_anchor_smooth_scroll/demo/pages.xml
  website_anchor_smooth_scroll/i18n/bg.po
  website_anchor_smooth_scroll/i18n/de.po
  website_anchor_smooth_scroll/i18n/es.po
  website_anchor_smooth_scroll/i18n/fr.po
  website_anchor_smooth_scroll/i18n/it.po
  website_anchor_smooth_scroll/i18n/pt_BR.po
  website_anchor_smooth_scroll/i18n/sl.po
  website_anchor_smooth_scroll/i18n/website_anchor_smooth_scroll.pot
  website_anchor_smooth_scroll/readme/CONTRIBUTORS.rst
  website_anchor_smooth_scroll/readme/DESCRIPTION.rst
  website_anchor_smooth_scroll/readme/INSTALL.rst
  website_anchor_smooth_scroll/readme/ROADMAP.rst
  website_anchor_smooth_scroll/readme/USAGE.rst
  website_anchor_smooth_scroll/static/description/icon.png
  website_anchor_smooth_scroll/static/src/js/website_anchor_smooth_scroll.js
  website_anchor_smooth_scroll/views/assets.xml
Labels: approved

#585 [FIX] website_form_builder: Fix missing required field indicators
  website_form_builder/__manifest__.py
  website_form_builder/templates/assets.xml
Labels: approved, bug
