Repository OCA/website, pull requests merged in 2019-01, with the labels that each got.

#536 [11.0][ADD] website_snippet_timeline
  website_snippet_timeline/README.rst
  website_snippet_timeline/__init__.py
  website_snippet_timeline/__manifest__.py
  website_snippet_timeline/readme/CONTRIBUTORS.rst
  website_snippet_timeline/readme/DESCRIPTION.rst
  website_snippet_timeline/readme/USAGE.rst
  website_snippet_timeline/static/description/screenshot-medium.png
  website_snippet_timeline/static/description/screenshot-small.png
  website_snippet_timeline/static/description/screenshot.png
  website_snippet_timeline/static/src/img/snippet-item.png
  website_snippet_timeline/static/src/img/snippet.png
  website_snippet_timeline/static/src/js/editor.js
  website_snippet_timeline/static/src/less/frontend.less
  website_snippet_timeline/templates/assets.xml
  website_snippet_timeline/templates/snippets.xml
Labels: approved, needs review

#563 [REF] website_form_recaptcha: better API, allow per-website config
  website_form_recaptcha/README.rst
  website_form_recaptcha/__manifest__.py
  website_form_recaptcha/controllers/main.py
  website_form_recaptcha/models/__init__.py
  website_form_recaptcha/models/website.py
  website_form_recaptcha/models/website_config_settings.py
  website_form_recaptcha/models/website_form_recaptcha.py
  website_form_recaptcha/readme/CONFIGURE.rst
  website_form_recaptcha/readme/CONTRIBUTORS.rst
  website_form_recaptcha/readme/DESCRIPTION.rst
  website_form_recaptcha/readme/HISTORY.rst
  website_form_recaptcha/readme/ROADMAP.rst
  website_form_recaptcha/readme/USAGE.rst
  website_form_recaptcha/static/description/index.html
  website_form_recaptcha/tests/test_captcha.py
  website_form_recaptcha/views/website.xml
  website_form_recaptcha/views/website_config_settings.xml
Labels: approved

#439 [11.0][ADD] website_video_preview
  website_video_preview/README.rst
  website_video_preview/__init__.py
  website_video_preview/__manifest__.py
  website_video_preview/readme/CONTRIBUTORS.rst
  website_video_preview/readme/DESCRIPTION.rst
  website_video_preview/readme/ROADMAP.rst
  website_video_preview/readme/USAGE.rst
  website_video_preview/static/src/img/yt_button.png
  website_video_preview/static/src/js/website_video_preview.editor.js
  website_video_preview/static/src/js/website_video_preview.frontend.js
  website_video_preview/static/src/less/website_video_preview.less
  website_video_preview/templates/assets.xml
Labels: approved, needs review, ready to merge

#566 website_form_recaptcha: fix and backward compat
  website_form_recaptcha/__manifest__.py
  website_form_recaptcha/models/website_form_recaptcha.py
  website_form_recaptcha/readme/HISTORY.rst
  website_form_recaptcha/tests/test_captcha.py
Labels: approved, needs review
