Repository OCA/website, pull requests merged in 2020-03, with the labels that each got.

#680 [13.0][MIG] website_video_preview
  .isort.cfg
  website_video_preview/README.rst
  website_video_preview/__init__.py
  website_video_preview/__manifest__.py
  website_video_preview/i18n/website_video_preview.pot
  website_video_preview/readme/CONTRIBUTORS.rst
  website_video_preview/readme/DESCRIPTION.rst
  website_video_preview/readme/ROADMAP.rst
  website_video_preview/readme/USAGE.rst
  website_video_preview/static/description/icon.png
  website_video_preview/static/description/index.html
  website_video_preview/static/src/img/yt_button.png
  website_video_preview/static/src/js/website_video_preview.editor.js
  website_video_preview/static/src/js/website_video_preview.frontend.js
  website_video_preview/static/src/scss/website_video_preview.scss
  website_video_preview/templates/assets.xml
Labels: approved, needs review, ready to merge

#703 [FIX] website_form_builder: restore functionality of required & hidden fields
  website_form_builder/migrations/11.0.1.2.0/post-migrate.py
  website_form_builder/static/src/js/snippets.js
  website_form_builder/static/src/js/tour.js
  website_form_builder/templates/snippets.xml
Labels: approved, bug, work in progress

#704 [FIX] website_form_builder: restore functionality of required & hidden fields
  website_form_builder/__manifest__.py
  website_form_builder/migrations/12.0.1.1.0/post-migrate.py
  website_form_builder/static/src/js/snippets.js
  website_form_builder/static/src/js/tour.js
  website_form_builder/templates/snippets.xml
Labels: bug
