Repository OCA/website, pull requests merged in 2020-07, with the labels that each got.

#738 [11.0][IMP] website_cookie_notice: remove not needed query
  website_cookie_notice/controllers/main.py
Labels: approved, bot is merging ⏳

#741 [IMP] website_form_builder: BS4 fixes and some improvements
  website_form_builder/static/src/css/website_form_builder.scss
  website_form_builder/static/src/js/snippets.js
  website_form_builder/static/src/xml/snippets.xml
Labels: approved, bot is merging ⏳, bug, enhancement

#742 [FIX] website_form_builder: duplicate radio and checkbox options
  website_form_builder/templates/snippets.xml
Labels: approved, bot is merging ⏳, bug, needs review

#736 [12.0][ADD] website_js_below_the_fold_payment
  website_js_below_the_fold_payment/__init__.py
  website_js_below_the_fold_payment/__manifest__.py
  website_js_below_the_fold_payment/readme/CONTRIBUTORS.rst
  website_js_below_the_fold_payment/readme/DESCRIPTION.rst
  website_js_below_the_fold_payment/readme/ROADMAP.rst
  website_js_below_the_fold_payment/templates/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#743 [FIX] website_snippet_anchor: use correct assets
  website_snippet_anchor/templates/assets.xml
Labels: approved, bot is merging ⏳, bug, needs review
