Repository OCA/website, pull requests merged in 2020-05, with the labels that each got.

#713 [13.0][MIG] website_cookie_notice: Migration to 13.0
  setup/website_cookie_notice/odoo/addons/website_cookie_notice
  setup/website_cookie_notice/setup.py
  website_cookie_notice/README.rst
  website_cookie_notice/__init__.py
  website_cookie_notice/__manifest__.py
  website_cookie_notice/controllers/__init__.py
  website_cookie_notice/controllers/main.py
  website_cookie_notice/hooks.py
  website_cookie_notice/i18n/bg.po
  website_cookie_notice/i18n/ca.po
  website_cookie_notice/i18n/de.po
  website_cookie_notice/i18n/el_GR.po
  website_cookie_notice/i18n/es.po
  website_cookie_notice/i18n/fr.po
  website_cookie_notice/i18n/gl.po
  website_cookie_notice/i18n/hr.po
  website_cookie_notice/i18n/hr_HR.po
  website_cookie_notice/i18n/it.po
  website_cookie_notice/i18n/nb_NO.po
  website_cookie_notice/i18n/nl.po
  website_cookie_notice/i18n/pt_BR.po
  website_cookie_notice/i18n/pt_PT.po
  website_cookie_notice/i18n/ru.po
  website_cookie_notice/i18n/sl.po
  website_cookie_notice/i18n/website_cookie_notice.pot
  website_cookie_notice/readme/CONFIGURE.rst
  website_cookie_notice/readme/CONTRIBUTORS.rst
  website_cookie_notice/readme/DESCRIPTION.rst
  website_cookie_notice/readme/ROADMAP.rst
  website_cookie_notice/static/description/icon.png
  website_cookie_notice/static/description/index.html
  website_cookie_notice/static/src/css/cookies.scss
  website_cookie_notice/static/src/js/accept_cookies.js
  website_cookie_notice/views/assets.xml
  website_cookie_notice/views/website.xml
Labels: approved, bot is merging ⏳, ready to merge

#720 [IMP] website_snippet_country_dropdown: readonly mode
  website_snippet_country_dropdown/demo/pages.xml
  website_snippet_country_dropdown/static/src/css/style.scss
  website_snippet_country_dropdown/static/src/js/web_tour_country_dropdown.js
  website_snippet_country_dropdown/static/src/js/website_snippet_country_dropdown.js
  website_snippet_country_dropdown/views/snippets.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#725 [FIX] website_canonical_url: use website domain
  website_canonical_url/models/website.py
Labels: approved, bot is merging ⏳, bug

#726 [12.0][ADD] website_megamenu
  website_megamenu/README.rst
  website_megamenu/__init__.py
  website_megamenu/__manifest__.py
  website_megamenu/models/__init__.py
  website_megamenu/models/website_menu.py
  website_megamenu/readme/CONTRIBUTORS.rst
  website_megamenu/readme/CREDITS.rst
  website_megamenu/readme/DESCRIPTION.rst
  website_megamenu/readme/ROADMAP.rst
  website_megamenu/readme/USAGE.rst
  website_megamenu/static/description/index.html
  website_megamenu/static/src/img/s_mega_menu_menu_image_menu.png
  website_megamenu/static/src/img/s_mega_menu_multi_menus.png
  website_megamenu/static/src/js/content.js
  website_megamenu/static/src/js/editor_menu.js
  website_megamenu/static/src/js/rte.js
  website_megamenu/static/src/js/snippets.editor.js
  website_megamenu/static/src/scss/website.scss
  website_megamenu/static/src/xml/website.contentMenu.xml
  website_megamenu/templates/assets.xml
  website_megamenu/templates/snippets.xml
  website_megamenu/templates/website.xml
Labels: approved, bot is merging ⏳, needs review
