Repository OCA/website, pull requests merged in 2021-04, with the labels that each got.

#831 [FIX] website_no_crawler: don't translate
  website_no_crawler/views/disable_robots.xml
Labels: approved

#833 [FIX] website_no_crawler: don't translate
  website_no_crawler/views/disable_robots.xml
Labels: bot is merging ⏳

#782 [FIX] website_legal_page: better visualization as required checkbox label
  website_legal_page/views/reusable_templates.xml
Labels: approved, bot is merging ⏳, ready to merge
