Repository OCA/website, pull requests merged in 2021-11, with the labels that each got.

#724 [13.0][ADD][website_cookiebot] New module for Cookiebot integration
  setup/website_cookiebot/odoo/addons/website_cookiebot
  setup/website_cookiebot/setup.py
  website_cookiebot/README.rst
  website_cookiebot/__init__.py
  website_cookiebot/__manifest__.py
  website_cookiebot/i18n/es.po
  website_cookiebot/i18n/website_cookiebot.pot
  website_cookiebot/models/__init__.py
  website_cookiebot/models/website.py
  website_cookiebot/readme/CONFIGURE.rst
  website_cookiebot/readme/CONTRIBUTORS.rst
  website_cookiebot/readme/DESCRIPTION.rst
  website_cookiebot/readme/USAGE.rst
  website_cookiebot/static/description/icon.png
  website_cookiebot/static/description/index.html
  website_cookiebot/static/description/screenshot.png
  website_cookiebot/templates/assets.xml
  website_cookiebot/templates/website.xml
  website_cookiebot/wizards/__init__.py
  website_cookiebot/wizards/res_config_settings.py
  website_cookiebot/wizards/res_config_settings_views.xml
Labels: needs review, bot is merging ⏳

#827 [14.0][MIG] website_cookiefirst: Cookiefirst integration
  setup/website_cookiefirst/odoo/addons/website_cookiefirst
  setup/website_cookiefirst/setup.py
  website_cookiefirst/__init__.py
  website_cookiefirst/__manifest__.py
  website_cookiefirst/data/cookies_policy.xml
  website_cookiefirst/models/__init__.py
  website_cookiefirst/models/res_config_settings.py
  website_cookiefirst/models/website.py
  website_cookiefirst/readme/CONFIGURE.rst
  website_cookiefirst/readme/CONTRIBUTORS.rst
  website_cookiefirst/readme/DESCRIPTION.rst
  website_cookiefirst/static/description/icon.png
  website_cookiefirst/views/portal_template.xml
  website_cookiefirst/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#815 [13.0][ADD] website_cookiefirst: Cookiefirst integration
  setup/website_cookiefirst/odoo/addons/website_cookiefirst
  setup/website_cookiefirst/setup.py
  website_cookiefirst/__init__.py
  website_cookiefirst/__manifest__.py
  website_cookiefirst/data/cookies_policy.xml
  website_cookiefirst/models/__init__.py
  website_cookiefirst/models/res_config_settings.py
  website_cookiefirst/models/website.py
  website_cookiefirst/readme/CONFIGURE.rst
  website_cookiefirst/readme/CONTRIBUTORS.rst
  website_cookiefirst/readme/DESCRIPTION.rst
  website_cookiefirst/static/description/icon.png
  website_cookiefirst/views/portal_template.xml
  website_cookiefirst/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#850 15.0 [MIG] website_odoo_debranding: Migration to 15.0
  setup/website_odoo_debranding/odoo/addons/website_odoo_debranding
  setup/website_odoo_debranding/setup.py
  website_odoo_debranding/README.rst
  website_odoo_debranding/__init__.py
  website_odoo_debranding/__manifest__.py
  website_odoo_debranding/hooks.py
  website_odoo_debranding/i18n/es_AR.po
  website_odoo_debranding/i18n/website_odoo_debranding.pot
  website_odoo_debranding/readme/CONTRIBUTORS.rst
  website_odoo_debranding/readme/DESCRIPTION.rst
  website_odoo_debranding/readme/USAGE.rst
  website_odoo_debranding/static/description/icon.png
  website_odoo_debranding/static/description/index.html
  website_odoo_debranding/templates/disable_odoo.xml
Labels: approved, bot is merging ⏳
