Repository OCA/website, pull requests merged in 2022-06, with the labels that each got.

#896 [ADD]website_snippet_timeline: Backport to 13.0
  setup/website_snippet_timeline/odoo/addons/website_snippet_timeline
  setup/website_snippet_timeline/setup.py
  website_snippet_timeline/README.rst
  website_snippet_timeline/__init__.py
  website_snippet_timeline/__manifest__.py
  website_snippet_timeline/readme/CONTRIBUTORS.rst
  website_snippet_timeline/readme/DESCRIPTION.rst
  website_snippet_timeline/readme/USAGE.rst
  website_snippet_timeline/static/description/icon.svg
  website_snippet_timeline/static/description/index.html
  website_snippet_timeline/static/src/js/options.js
  website_snippet_timeline/static/src/scss/000.scss
  website_snippet_timeline/templates/assets.xml
  website_snippet_timeline/templates/snippets.xml
Labels: approved, ready to merge, bot is merging ⏳

#901 [15.0][IMP] website_odoo_debranding: Avoid deprecation warning with 'Enviro…
  website_odoo_debranding/hooks.py
Labels: bot is merging ⏳

#895 [MIG] website_crm_privacy_policy: Migration to 15.0
  setup/website_crm_privacy_policy/odoo/addons/website_crm_privacy_policy
  setup/website_crm_privacy_policy/setup.py
  website_crm_privacy_policy/README.rst
  website_crm_privacy_policy/__init__.py
  website_crm_privacy_policy/__manifest__.py
  website_crm_privacy_policy/i18n/ca.po
  website_crm_privacy_policy/i18n/de.po
  website_crm_privacy_policy/i18n/el_GR.po
  website_crm_privacy_policy/i18n/es.po
  website_crm_privacy_policy/i18n/fr.po
  website_crm_privacy_policy/i18n/it.po
  website_crm_privacy_policy/i18n/pt_BR.po
  website_crm_privacy_policy/i18n/ru.po
  website_crm_privacy_policy/i18n/sl.po
  website_crm_privacy_policy/i18n/website_crm_privacy_policy.pot
  website_crm_privacy_policy/readme/CONTRIBUTORS.rst
  website_crm_privacy_policy/readme/CREDITS.rst
  website_crm_privacy_policy/readme/DESCRIPTION.rst
  website_crm_privacy_policy/readme/USAGE.rst
  website_crm_privacy_policy/static/description/icon.png
  website_crm_privacy_policy/static/description/index.html
  website_crm_privacy_policy/templates/contactus.xml
Labels: approved, ready to merge, bot is merging ⏳

#903 [13.0][FIX] website_cookiefirst: resource loading
  website_cookiefirst/views/portal_template.xml
Labels: approved, bot is merging ⏳
