Repository OCA/website, pull requests merged in 2022-12, with the labels that each got.

#930 [15.0][MIG] website_plausible
  setup/website_plausible/odoo/addons/website_plausible
  setup/website_plausible/setup.py
  website_plausible/README.rst
  website_plausible/__init__.py
  website_plausible/__manifest__.py
  website_plausible/i18n/website_plausible.pot
  website_plausible/models/__init__.py
  website_plausible/models/res_config_settings.py
  website_plausible/models/website.py
  website_plausible/readme/CONFIGURE.rst
  website_plausible/readme/CONTRIBUTORS.rst
  website_plausible/readme/DESCRIPTION.rst
  website_plausible/readme/ROADMAP.rst
  website_plausible/static/description/icon.png
  website_plausible/static/description/index.html
  website_plausible/views/templates.xml
  website_plausible/views/website_config_settings.xml
Labels: approved, bot is merging ⏳

#924 [14.0][MIG] website_no_crawler
  setup/website_no_crawler/odoo/addons/website_no_crawler
  setup/website_no_crawler/setup.py
  website_no_crawler/README.rst
  website_no_crawler/__init__.py
  website_no_crawler/__manifest__.py
  website_no_crawler/controllers/__init__.py
  website_no_crawler/controllers/main.py
  website_no_crawler/data/data.xml
  website_no_crawler/i18n/ca.po
  website_no_crawler/i18n/es.po
  website_no_crawler/i18n/hr.po
  website_no_crawler/i18n/nl.po
  website_no_crawler/i18n/website_no_crawler.pot
  website_no_crawler/readme/CONFIGURE.rst
  website_no_crawler/readme/CONTRIBUTORS.rst
  website_no_crawler/readme/DESCRIPTION.rst
  website_no_crawler/readme/USAGE.rst
  website_no_crawler/static/description/icon.png
  website_no_crawler/static/description/index.html
  website_no_crawler/views/disable_robots.xml
Labels: approved, ready to merge, bot is merging ⏳

#931 [14.0][FIX] website_no_crawler, config param id
  website_no_crawler/controllers/main.py
  website_no_crawler/data/data.xml
Labels: bot is merging ⏳

#921 [16.0][MIG] website_odoo_debranding
  setup/website_odoo_debranding/odoo/addons/website_odoo_debranding
  setup/website_odoo_debranding/setup.py
  website_odoo_debranding/README.rst
  website_odoo_debranding/__init__.py
  website_odoo_debranding/__manifest__.py
  website_odoo_debranding/hooks.py
  website_odoo_debranding/i18n/es_AR.po
  website_odoo_debranding/i18n/website_odoo_debranding.pot
  website_odoo_debranding/readme/CONTRIBUTORS.rst
  website_odoo_debranding/readme/DESCRIPTION.rst
  website_odoo_debranding/readme/USAGE.rst
  website_odoo_debranding/static/description/icon.png
  website_odoo_debranding/static/description/index.html
  website_odoo_debranding/templates/disable_odoo.xml
Labels: approved, ready to merge, bot is merging ⏳
