Repository OCA/website, pull requests merged in 2022-05, with the labels that each got.

#886 [15.0][MIG]website_crm_quick_answer
  setup/website_crm_quick_answer/odoo/addons/website_crm_quick_answer
  setup/website_crm_quick_answer/setup.py
  website_crm_quick_answer/README.rst
  website_crm_quick_answer/__init__.py
  website_crm_quick_answer/__manifest__.py
  website_crm_quick_answer/data/base_automation_data.xml
  website_crm_quick_answer/i18n/website_crm_quick_answer.pot
  website_crm_quick_answer/readme/CONFIGURE.rst
  website_crm_quick_answer/readme/CONTRIBUTORS.rst
  website_crm_quick_answer/readme/DESCRIPTION.rst
  website_crm_quick_answer/readme/USAGE.rst
  website_crm_quick_answer/static/description/icon.png
  website_crm_quick_answer/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#745 [ADD] website_menu_icon
  setup/website_menu_icon/odoo/addons/website_menu_icon
  setup/website_menu_icon/setup.py
  website_menu_icon/README.rst
  website_menu_icon/__init__.py
  website_menu_icon/__manifest__.py
  website_menu_icon/models/__init__.py
  website_menu_icon/models/website_menu.py
  website_menu_icon/readme/CONFIGURE.rst
  website_menu_icon/readme/CONTRIBUTORS.rst
  website_menu_icon/readme/DESCRIPTION.rst
  website_menu_icon/static/description/edit_item.png
  website_menu_icon/static/description/edit_menu.png
  website_menu_icon/static/description/index.html
  website_menu_icon/static/description/menu_sample.png
  website_menu_icon/static/src/js/content.js
  website_menu_icon/static/src/xml/website.contentMenu.xml
  website_menu_icon/views/assets.xml
  website_menu_icon/views/website_menu_icon.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#889 [15.0][MIG] website_snippet_country_dropdown: Migration to 15.0
  setup/website_snippet_country_dropdown/odoo/addons/website_snippet_country_dropdown
  setup/website_snippet_country_dropdown/setup.py
  website_snippet_country_dropdown/README.rst
  website_snippet_country_dropdown/__init__.py
  website_snippet_country_dropdown/__manifest__.py
  website_snippet_country_dropdown/demo/pages.xml
  website_snippet_country_dropdown/i18n/en.po
  website_snippet_country_dropdown/i18n/es.po
  website_snippet_country_dropdown/i18n/fr.po
  website_snippet_country_dropdown/i18n/sl.po
  website_snippet_country_dropdown/i18n/website_snippet_country_dropdown.pot
  website_snippet_country_dropdown/readme/CONTRIBUTORS.rst
  website_snippet_country_dropdown/readme/DESCRIPTION.rst
  website_snippet_country_dropdown/readme/ROADMAP.rst
  website_snippet_country_dropdown/readme/USAGE.rst
  website_snippet_country_dropdown/static/description/icon.png
  website_snippet_country_dropdown/static/description/index.html
  website_snippet_country_dropdown/static/src/css/style.scss
  website_snippet_country_dropdown/static/src/js/web_tour_country_dropdown.js
  website_snippet_country_dropdown/static/src/js/website_snippet_country_dropdown.js
  website_snippet_country_dropdown/static/src/xml/country_dropdown.xml
  website_snippet_country_dropdown/tests/__init__.py
  website_snippet_country_dropdown/tests/test_snippet_country_dropdown.py
  website_snippet_country_dropdown/views/snippets.xml
Labels: approved, ready to merge, bot is merging ⏳

#559 [12.0][MIG] website_menu_by_user_status
  website_menu_by_user_status/README.rst
  website_menu_by_user_status/__init__.py
  website_menu_by_user_status/__manifest__.py
  website_menu_by_user_status/i18n/website_menu_by_user_status.pot
  website_menu_by_user_status/models/__init__.py
  website_menu_by_user_status/models/website_menu.py
  website_menu_by_user_status/readme/CONTRIBUTORS.rst
  website_menu_by_user_status/readme/DESCRIPTION.rst
  website_menu_by_user_status/readme/ROADMAP.rst
  website_menu_by_user_status/readme/USAGE.rst
  website_menu_by_user_status/static/description/icon.png
  website_menu_by_user_status/tests/__init__.py
  website_menu_by_user_status/tests/test_website_menu.py
  website_menu_by_user_status/views/website_menu.xml
Labels: needs fixing, approved, bot is merging ⏳

#897 [15.0][MIG] website_legal_page: Migration to 15.0
  setup/website_legal_page/odoo/addons/website_legal_page
  setup/website_legal_page/setup.py
  website_legal_page/README.rst
  website_legal_page/__init__.py
  website_legal_page/__manifest__.py
  website_legal_page/controllers/__init__.py
  website_legal_page/controllers/main.py
  website_legal_page/hooks.py
  website_legal_page/i18n/bg.po
  website_legal_page/i18n/ca.po
  website_legal_page/i18n/de.po
  website_legal_page/i18n/el_GR.po
  website_legal_page/i18n/es.po
  website_legal_page/i18n/es_AR.po
  website_legal_page/i18n/fr.po
  website_legal_page/i18n/hr_HR.po
  website_legal_page/i18n/it.po
  website_legal_page/i18n/nb_NO.po
  website_legal_page/i18n/pt_BR.po
  website_legal_page/i18n/pt_PT.po
  website_legal_page/i18n/ru.po
  website_legal_page/i18n/sl.po
  website_legal_page/i18n/website_legal_page.pot
  website_legal_page/readme/CONTRIBUTORS.rst
  website_legal_page/readme/CREDITS.rst
  website_legal_page/readme/DESCRIPTION.rst
  website_legal_page/readme/USAGE.rst
  website_legal_page/static/description/icon.png
  website_legal_page/static/description/index.html
  website_legal_page/static/description/johnny-automatic-scales-of-justice.svg
  website_legal_page/static/src/css/website_legal_page.scss
  website_legal_page/tests/__init__.py
  website_legal_page/tests/test_controller.py
  website_legal_page/views/reusable_templates.xml
  website_legal_page/views/website_legal_main_page.xml
Labels: approved, bot is merging ⏳
