Repository OCA/website, pull requests merged in 2023-10, with the labels that each got.

#1010 [16.0][MIG] website_forum_subscription: Migration to version 16.0
  setup/website_forum_subscription/odoo/addons/website_forum_subscription
  setup/website_forum_subscription/setup.py
  website_forum_subscription/README.rst
  website_forum_subscription/__init__.py
  website_forum_subscription/__manifest__.py
  website_forum_subscription/i18n/es.po
  website_forum_subscription/i18n/it.po
  website_forum_subscription/i18n/website_forum_subscription.pot
  website_forum_subscription/readme/CONTRIBUTORS.rst
  website_forum_subscription/readme/DESCRIPTION.rst
  website_forum_subscription/readme/USAGE.rst
  website_forum_subscription/static/description/icon.png
  website_forum_subscription/static/description/index.html
  website_forum_subscription/templates/website_forum_templates.xml
Labels: approved, bot is merging ⏳

#1013 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  website_odoo_debranding/templates/disable_odoo.xml
Labels: help wanted, needs review

#943 [MIG] website_whatsapp: Migration to 16.0
  setup/website_whatsapp/odoo/addons/website_whatsapp
  setup/website_whatsapp/setup.py
  website_whatsapp/README.rst
  website_whatsapp/__init__.py
  website_whatsapp/__manifest__.py
  website_whatsapp/i18n/website_whatsapp.pot
  website_whatsapp/models/__init__.py
  website_whatsapp/models/res_config_settings.py
  website_whatsapp/models/website.py
  website_whatsapp/readme/CONFIGURE.rst
  website_whatsapp/readme/CONTRIBUTORS.rst
  website_whatsapp/readme/DESCRIPTION.rst
  website_whatsapp/static/description/icon.png
  website_whatsapp/static/description/index.html
  website_whatsapp/static/src/scss/website.scss
  website_whatsapp/templates/website.xml
  website_whatsapp/views/res_config_settings.xml
Labels: bot is merging ⏳
