Repository OCA/website, pull requests merged in 2023-03, with the labels that each got.

#946 [16.0][MIG] website_legal_page: migration to 16.0
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  setup/website_legal_page/odoo/addons/website_legal_page
  setup/website_legal_page/setup.py
  website_legal_page/README.rst
  website_legal_page/__init__.py
  website_legal_page/__manifest__.py
  website_legal_page/i18n/bg.po
  website_legal_page/i18n/ca.po
  website_legal_page/i18n/de.po
  website_legal_page/i18n/el_GR.po
  website_legal_page/i18n/es.po
  website_legal_page/i18n/es_AR.po
  website_legal_page/i18n/fr.po
  website_legal_page/i18n/hr_HR.po
  website_legal_page/i18n/it.po
  website_legal_page/i18n/nb_NO.po
  website_legal_page/i18n/pt_BR.po
  website_legal_page/i18n/pt_PT.po
  website_legal_page/i18n/ru.po
  website_legal_page/i18n/sl.po
  website_legal_page/i18n/website_legal_page.pot
  website_legal_page/readme/CONTRIBUTORS.rst
  website_legal_page/readme/CREDITS.rst
  website_legal_page/readme/DESCRIPTION.rst
  website_legal_page/readme/USAGE.rst
  website_legal_page/static/description/icon.png
  website_legal_page/static/description/index.html
  website_legal_page/static/description/johnny-automatic-scales-of-justice.svg
  website_legal_page/static/src/css/website_legal_page.scss
  website_legal_page/tests/__init__.py
  website_legal_page/tests/test_controller.py
  website_legal_page/views/website_legal_main_page.xml
Labels: bot is merging ⏳

#942 [ADD] website_require_login.
  setup/website_require_login/odoo/addons/website_require_login
  setup/website_require_login/setup.py
  website_require_login/README.rst
  website_require_login/__init__.py
  website_require_login/__manifest__.py
  website_require_login/data/ir_actions.xml
  website_require_login/data/ir_ui_menu.xml
  website_require_login/models/__init__.py
  website_require_login/models/ir_http.py
  website_require_login/models/website_auth_url.py
  website_require_login/readme/CONTRIBUTORS.rst
  website_require_login/readme/DESCRIPTION.rst
  website_require_login/readme/USAGE.rst
  website_require_login/security/ir.model.access.csv
  website_require_login/static/description/icon.png
  website_require_login/tests/__init__.py
  website_require_login/tests/test_ir_http.py
  website_require_login/views/website_auth_url.xml
Labels: approved, ready to merge, bot is merging ⏳

#963 [15.0][ADD] website_form_require_legal: New module to add terms acceptance at website form level
  __init__.py
  setup/website_form_require_legal/odoo/addons/website_form_require_legal
  setup/website_form_require_legal/setup.py
  website_form_require_legal/README.rst
  website_form_require_legal/__init__.py
  website_form_require_legal/__manifest__.py
  website_form_require_legal/i18n/es.po
  website_form_require_legal/i18n/website_form_require_legal.pot
  website_form_require_legal/readme/CONTRIBUTORS.rst
  website_form_require_legal/readme/DESCRIPTION.rst
  website_form_require_legal/readme/ROADMAP.rst
  website_form_require_legal/readme/USAGE.rst
  website_form_require_legal/static/description/index.html
  website_form_require_legal/static/src/js/options.js
  website_form_require_legal/static/src/scss/website_form_legal.scss
  website_form_require_legal/static/src/xml/website_form_editor.xml
  website_form_require_legal/views/snippets.xml
Labels: approved, ready to merge, bot is merging ⏳

#964 [15.0][IMP] website_crm_privacy_policy: Mark it as deprecated
  website_crm_privacy_policy/README.rst
  website_crm_privacy_policy/readme/DESCRIPTION.rst
  website_crm_privacy_policy/static/description/index.html
Labels: approved, bot is merging ⏳

#965 [15.0][MIG] website_forum_subscription: Migration to version 15.0
  setup/website_forum_subscription/odoo/addons/website_forum_subscription
  setup/website_forum_subscription/setup.py
  website_forum_subscription/README.rst
  website_forum_subscription/__init__.py
  website_forum_subscription/__manifest__.py
  website_forum_subscription/i18n/es.po
  website_forum_subscription/i18n/it.po
  website_forum_subscription/i18n/website_forum_subscription.pot
  website_forum_subscription/readme/CONTRIBUTORS.rst
  website_forum_subscription/readme/DESCRIPTION.rst
  website_forum_subscription/readme/USAGE.rst
  website_forum_subscription/static/description/icon.png
  website_forum_subscription/static/description/index.html
  website_forum_subscription/templates/website_forum_templates.xml
Labels: approved, bot is merging ⏳

#967 [15.0][FIX] website_crm_privacy_policy: Fixed error calling a template that does not exist
  website_crm_privacy_policy/templates/contactus.xml
Labels: approved, bot is merging ⏳
