Repository OCA/website, pull requests merged in 2023-07, with the labels that each got.

#985 [16.0][MIG] website_require_login: Migration to 16.0
  setup/website_require_login/odoo/addons/website_require_login
  setup/website_require_login/setup.py
  website_require_login/README.rst
  website_require_login/__init__.py
  website_require_login/__manifest__.py
  website_require_login/data/ir_actions.xml
  website_require_login/data/ir_ui_menu.xml
  website_require_login/i18n/it.po
  website_require_login/i18n/website_require_login.pot
  website_require_login/models/__init__.py
  website_require_login/models/ir_http.py
  website_require_login/models/website_auth_url.py
  website_require_login/readme/CONTRIBUTORS.rst
  website_require_login/readme/DESCRIPTION.rst
  website_require_login/readme/USAGE.rst
  website_require_login/security/ir.model.access.csv
  website_require_login/static/description/icon.png
  website_require_login/static/description/index.html
  website_require_login/tests/__init__.py
  website_require_login/tests/test_ir_http.py
  website_require_login/views/website_auth_url.xml
Labels: approved, ready to merge, bot is merging ⏳

#992 [15.0][IMP] website_plausible: Added docs for configuration if Plausible is self-hosted
  website_plausible/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳

#996 [13.0][FIX] website_google_analytics_4 mime type
  website_google_analytics_4/views/website_templates.xml
Labels: approved, bot is merging ⏳

#998 [16.0][FIX] website_crm_privacy_policy: Fixed error calling a template that…
  website_crm_privacy_policy/templates/contactus.xml
Labels: bot is merging ⏳
