Repository OCA/website, pull requests merged in 2024-08, with the labels that each got.

#1052 [FIX] website_google_tag_manager: fix hidden menu behavior with tag manager
  website_google_tag_manager/views/website_templates.xml
Labels: bot is merging ⏳

#1055 [16.0][FIX] website_cookiebot: disable for sure
  website_cookiebot/__manifest__.py
  website_cookiebot/migrations/16.0.2.0.0/post-migrate.py
  website_cookiebot/models/website.py
  website_cookiebot/templates/assets.xml
  website_cookiebot/templates/website.xml
  website_cookiebot/wizards/res_config_settings.py
Labels: approved, bot is merging ⏳

#1054 [FIX] website_google_tag_manager: fix hidden menu behavior with tag manager
  website_google_tag_manager/views/website_templates.xml
Labels: bot is merging ⏳

#1053 [FIX] website_google_tag_manager: fix hidden menu behavior with tag manager
  website_google_tag_manager/views/website_templates.xml
Labels: bot is merging ⏳

#1044 [MIG][17.0] website_cookiebot
  website_cookiebot/README.rst
  website_cookiebot/__init__.py
  website_cookiebot/__manifest__.py
  website_cookiebot/i18n/de.po
  website_cookiebot/i18n/es.po
  website_cookiebot/i18n/it.po
  website_cookiebot/i18n/website_cookiebot.pot
  website_cookiebot/models/__init__.py
  website_cookiebot/models/website.py
  website_cookiebot/pyproject.toml
  website_cookiebot/readme/CONFIGURE.md
  website_cookiebot/readme/CONTRIBUTORS.md
  website_cookiebot/readme/DESCRIPTION.md
  website_cookiebot/readme/USAGE.md
  website_cookiebot/static/description/icon.png
  website_cookiebot/static/description/index.html
  website_cookiebot/static/description/screenshot.png
  website_cookiebot/templates/assets.xml
  website_cookiebot/templates/website.xml
  website_cookiebot/tests/__init__.py
  website_cookiebot/tests/test_website_cookiebot.py
  website_cookiebot/wizards/__init__.py
  website_cookiebot/wizards/res_config_settings.py
  website_cookiebot/wizards/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1020 [17.0][MIG] website_form_require_legal: Migration to 17.0
  website_form_require_legal/README.rst
  website_form_require_legal/__init__.py
  website_form_require_legal/__manifest__.py
  website_form_require_legal/i18n/de.po
  website_form_require_legal/i18n/es.po
  website_form_require_legal/i18n/it.po
  website_form_require_legal/i18n/website_form_require_legal.pot
  website_form_require_legal/pyproject.toml
  website_form_require_legal/readme/CONTRIBUTORS.md
  website_form_require_legal/readme/DESCRIPTION.md
  website_form_require_legal/readme/ROADMAP.md
  website_form_require_legal/readme/USAGE.md
  website_form_require_legal/static/description/icon.png
  website_form_require_legal/static/description/index.html
  website_form_require_legal/static/src/js/options.esm.js
  website_form_require_legal/static/src/scss/website_form_legal.scss
  website_form_require_legal/static/src/xml/website_form_editor.xml
  website_form_require_legal/views/snippets.xml
Labels: approved, ready to merge, bot is merging ⏳
